name: Matrix
on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
        include:
          - os: windows-latest
            node_version: 10
            is_win_10: "true"
        exclude:
          - os: macos-latest
            node_version: 6
          - os: ubuntu-latest
            node_version: 8
    runs-on: ${{ matrix.os }}
    env:
      IS_WIN_10: ${{ matrix.is_win_10 }}
    steps:
      - name: Log default node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log installed node version
        run: |
          node -v
          echo $IS_WIN_10