on: push
jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Jerry"
      - run: |
          echo "Greeting Time: ${{ steps.hello.outputs.time }}"