name: Run simple action
on: 
  push: 
  pull_request:
    types: [opened, reopened, assigned, closed]
jobs:
  run-github-action:
    runs-on: ubuntu-latest
    name: Run Greeting Action
    steps:
      - name: Print a greeting to
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Artyom
      - name: Log greetng time
        run: echo "${{ steps.greet.outputs.time }}"
