name: Run simple shell commands
on: 
  push:
  #schedule:
  # - cron: "0/5 * * * *"
  repository_dispatch:
    types: [build]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    name: Run Shell Command
    steps:
      - name: Echo simple string
        run: echo "This is a simple test string"
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Run multiline commands
        run: |
          node -v
          npm -v
          pwd
          ls
          env
          echo ${{ github.event.client_payload.env }}
      - name: Run python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    name: Run Windows Command
    needs: ["run-shell-command"]
    steps:
      - name: Get Directory Powershell
        run: Get-Location
      - name: Get Directory Bash
        run: pwd
        shell: bash
