name: Run simple shell command and Do A Security scan
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    name: Run Shell Command
    steps:
      - name: Echo simple string
        run: echo "This is a simple test string"
      - name: Run multiline commands
        run: | 
          node -v
          npm -v
      - name: Run python command
        run: | 
          import platform
          print(platform.processor())
        shell: python  
